config/routes.rb
Rails.application.routes.draw do
  #these constraints are for when we figure out the associations with users to students, programdirectors, professors/advisors
   # constraints Clearance::Constraints::SignedIn.new { |user| user.programdirectors? } do
   # root to: "programdirectors/dashboards#show", as: :programdirectors_root
  #end

 # constraints Clearance::Constraints::SignedIn.new { |user| user.professors? } do
  #  root to: "professors/dashboards#show", as: :professors_root
 # end

 # constraints Clearance::Constraints::SignedIn.new { |user| user.students? } do
  #  root to: "students/dashboards#show", as: :students_root
 # end
  
  resources :notes
  
  resources :comments
  
  resources :discussions
  
  resources :programdirectors
  
  #adds a path under professors: example: https://myappname.com/professors/professorid/student/studentsid
  resources :professors do 
   resources :students
  end
  
  resources :plans
  
  resources :welcome
  
  #adds a path under students: example: https://myappname.com/students/studentid/plan/planid
  resources :students do
   resources :plans
  end
  
  resources :semesters do
   resources :courses, only: [:new, :create, :destroy]
  end
  resources :courses

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  
  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    root to: "landingpage#show", as: :admin_root
  end

  constraints Clearance::Constraints::SignedIn.new do
    root to: "landingpage#show", as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: "landingpage#show"
  end
  
  # get '/', to: 'welcome#index', as: :root
  # get '/sign_up', to: 'users#new', as: :register
  # get '/sign_in', to: 'sessions#new', as: :sign_in
  # post '/login', to: 'sessions#create'
  
  resources :users, only: [:edit, :show, :update]

end

app/models/ability.rb
class Ability
  include CanCan::Ability
#if you are going to use these in the show.html.erb you need to put above the <%link_to 
#<%if can? :actionperform, @model you want to perform it on checking users ability

#also in the controller.rb of function like def edit you would have to put at the bottom

#of the method unauthorized! if cannot? 
  alias_action :create, :read, :update, :destroy, to: :crud
  
  def initialize(user)
  can :read, :all 
  end 
  
end

  
  
  
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :student, class_name => 'User'
  belongs_to :professor, class_name => 'User'
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :course_semesters
    has_many :courses, through: :course_semesters
    validates :name, presence: true
    validates :dept, presence: true
    validates :number, presence: true
    validates :description, presence: true
end

app/models/course_semester.rb
class CourseSemester < ApplicationRecord
    belongs_to :semester
    belongs_to :course
end

app/models/discussion.rb
class Discussion < ApplicationRecord
    has_many :comments
    validates :title, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/plan.rb
class Plan < ApplicationRecord
    belongs_to :student, optional: true
    has_many :semesters
    has_many :courses, through: :semesters
end

app/models/professor.rb
class Professor < ApplicationRecord
    has_many :students
    belongs_to :programdirector
    #belongs_to :users
end

app/models/programdirector.rb
class Programdirector < ApplicationRecord
    has_many :professors
    #belongs_to :users
end

app/models/semester.rb
class Semester < ApplicationRecord
 belongs_to :user
 has_many :course_semesters
 has_many :courses, through: :course_semesters
 validates_presence_of :name
end

app/models/student.rb
class Student < ApplicationRecord
    #belongs_to :users
    has_many :plans
    belongs_to :professor
    #has_many :semesters, through: :plans
   # has_many :courses, through: :semesters
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  validates_presence_of :email, :encrypted_password
  has_many :comments
  has_many :semesters
  # has_many :users, :class_name => 'Student', :foreign_key => 'student_id'
  # has_many :advisors, :class_name => 'Professor', :foreign_key => 'advisor_id'
  
  ROLES = ['Student', 'Professor', 'Director', 'Admin']

  enum role: ["Student", "Professor", "Director", "Admin"]
  
  def self.students
    User.where(role: "Student")
  end
  
  def advisor
    User.find(self.advisor_id)
  end
  
  def students
    User.where(advisor_id: self.id)
  end
  
  def student?
    self.role == "Student"
  end
  
  def admin?
    self.role == "Admin"
  end
  
  def self.professors
    User.where(role: "Professor")
  end
  
  private
  
  def user_params
    params.require(:user).permit(
      :email, 
      :password, 
      :role
    )
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= Notes %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<html>
    
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<script>
    
  .w3-teal, .w3-hover-teal:hover {
      background-color: #1F3A60!important;
  }
    
</script>
    
    
<body>
    
<!-- Sidebar -->    
<div class="w3-sidebar w3-light-grey w3-bar-block" style="background-color: #1A3152!important; color:white;">
  <h3 class="w3-bar-item">Menu</h3>
   <a href="<%= students_path  %>" class="w3-bar-item w3-button" style="color:white!important;font-weight:bold;background-color: #3975B7!important;">STUDENTS</a>
 <a href="<%=professors_path %>" class="w3-bar-item w3-button" style="color:white!important;font-weight:bold;background-color: #3975B7!important;">ADVISORS</a>
  <a href="<%= programdirectors_path %>" class="w3-bar-item w3-button" style="color:white!important;font-weight:bold;background-color: #3975B7!important;">PROGRAM DIRECTORS</a>
 <a href="<%=semesters_path %>" class="w3-bar-item w3-button" style="color:white!important;font-weight:bold;background-color: #3975B7!important;">SEMESTERS</a>
  <a href="<%= comments_path %>" class="w3-bar-item w3-button" style="color:white!important;font-weight:bold;background-color: #3975B7!important;">COMMENTS</a>
    <a href="<%= discussions_path %>" class="w3-bar-item w3-button" style="color:white!important;font-weight:bold;background-color: #3975B7!important;">E-MAILS</a>
</div>
  
<div id="main">
    
<div class="w3-teal" style="background-color: #1A3152!important;">
  <button id="openNav" class="w3-button w3-teal w3-xlarge" style="background-color: #1A3152!important; padding-left: 2%; padding-bottom: 0px; font-weight: bold;color:white!important;" onclick="w3_open()">Menu</button>
  <div class="w3-container">
    <h1></h1>
  </div>
</div>
    
<script>
function w3_open() {
  document.getElementById("main").style.marginLeft = "10%";
  document.getElementById("mySidebar").style.width = "10%";
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("openNav").style.display = 'none';
}

function w3_close() {
  document.getElementById("main").style.marginLeft = "0%";
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("openNav").style.display = "inline-block";
}
</script>
p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>