config/routes.rb
Rails.application.routes.draw do
  #these constraints are for when we figure out the associations with users to students, programdirectors, professors/advisors
   # constraints Clearance::Constraints::SignedIn.new { |user| user.programdirectors? } do
   # root to: "programdirectors/dashboards#show", as: :programdirectors_root
  #end

 # constraints Clearance::Constraints::SignedIn.new { |user| user.professors? } do
  #  root to: "professors/dashboards#show", as: :professors_root
 # end

 # constraints Clearance::Constraints::SignedIn.new { |user| user.students? } do
  #  root to: "students/dashboards#show", as: :students_root
 # end
  
  resources :notes
  
  resources :comments
  
  resources :discussions
  
  resources :programdirectors
  
  #adds a path under professors: example: https://myappname.com/professors/professorid/student/studentsid
  resources :professors do 
   resources :students
  end
  
  resources :plans
  
  resources :welcome
  
  #adds a path under students: example: https://myappname.com/students/studentid/plan/planid
  resources :students do
   resources :plans
  end
  
  resources :semesters do
   resources :courses, only: [:new, :create, :destroy]
  end
  resources :courses

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  
  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    root to: "landingpage#show", as: :admin_root
  end

  constraints Clearance::Constraints::SignedIn.new do
    root to: "landingpage#show", as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: "landingpage#show"
  end
  
  # get '/', to: 'welcome#index', as: :root
  # get '/sign_up', to: 'users#new', as: :register
  # get '/sign_in', to: 'sessions#new', as: :sign_in
  # post '/login', to: 'sessions#create'
  
  resources :users, only: [:edit, :show, :update]

end

app/models/ability.rb
class Ability
  include CanCan::Ability
#if you are going to use these in the show.html.erb you need to put above the <%link_to 
#<%if can? :actionperform, @model you want to perform it on checking users ability

#also in the controller.rb of function like def edit you would have to put at the bottom

#of the method unauthorized! if cannot? 
  alias_action :create, :read, :update, :destroy, to: :crud
  
  def initialize(user)
  can :read, :all 
  end 
  
end

  
  
  
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :student, class_name => 'User'
  belongs_to :professor, class_name => 'User'
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :course_semesters
    has_many :courses, through: :course_semesters
    validates :name, presence: true
    validates :dept, presence: true
    validates :number, presence: true
    validates :description, presence: true
end

app/models/course_semester.rb
class CourseSemester < ApplicationRecord
    belongs_to :semester
    belongs_to :course
end

app/models/discussion.rb
class Discussion < ApplicationRecord
    has_many :comments
    validates :title, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/plan.rb
class Plan < ApplicationRecord
    belongs_to :student, optional: true
    has_many :semesters
    has_many :courses, through: :semesters
end

app/models/professor.rb
class Professor < ApplicationRecord
    has_many :students
    belongs_to :programdirector
    #belongs_to :users
end

app/models/programdirector.rb
class Programdirector < ApplicationRecord
    has_many :professors
    #belongs_to :users
end

app/models/semester.rb
class Semester < ApplicationRecord
 belongs_to :user
 has_many :course_semesters
 has_many :courses, through: :course_semesters
 validates_presence_of :name
end

app/models/student.rb
class Student < ApplicationRecord
    #belongs_to :users
    has_many :plans
    belongs_to :professor
    #has_many :semesters, through: :plans
   # has_many :courses, through: :semesters
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  validates_presence_of :email, :encrypted_password
  has_many :comments
  has_many :semesters
  # has_many :users, :class_name => 'Student', :foreign_key => 'student_id'
  # has_many :advisors, :class_name => 'Professor', :foreign_key => 'advisor_id'
  
  ROLES = ['Student', 'Professor', 'Director', 'Admin']

  enum role: ["Student", "Professor", "Director", "Admin"]
  
  def self.students
    User.where(role: "Student")
  end
  
  def advisor
    User.find(self.advisor_id)
  end
  
  def students
    User.where(advisor_id: self.id)
  end
  
  def student?
    self.role == "Student"
  end
  
  def admin?
    self.role == "Admin"
  end
  
  def self.professors
    User.where(role: "Professor")
  end
  
  private
  
  def user_params
    params.require(:user).permit(
      :email, 
      :password, 
      :role
    )
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[edit update destroy ]

  # GET /students or /students.json
  def index
    @students = User.students
  end

  # GET /students/1 or /students/1.json
  def show
    @student = User.find(params[:id])
    @semesters = @student.semesters
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:Name, :CWID, :Concentration, :Advisor, :professor_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="field">
    <%= form.label :CWID %>
    <%= form.number_field :CWID %>
  </div>

  <div class="field">
    <%= form.label :Concentration %>
    <%= form.text_field :Concentration %>
  </div>

  <div class="control-group">
    <%= form.label "Advisors", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:Advisor, options_from_collection_for_select(Professor.all, 'Name', 'Name')) %>
    </div>
  </div>
  
  <div class="field">
    <%= form.label "Professor ID" %>
    <%= form.number_field :professor_id %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cwid</th>
      <th>Concentration</th>
      <th>Advisor</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.name, student_path(student) %></td>
        <td><%= student.cwid %></td>
        <td><%= student.concentration %></td>
        <% if student.advisor_id %>
          <% advisor = student.advisor %>
          <td><%= link_to advisor.name, professor_path(advisor) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/old_show.html.erb
<p id="notice"><%= notice %></p>

<h1>Student: <%= @student.Name %></h1>

<p>
  <strong>Cwid:</strong>
  <%= @student.CWID %>
</p>

<p>
  <strong>Concentration:</strong>
  <%= @student.Concentration %>
</p>

<p>
  <strong>Advisor:</strong>
  <%= @student.Advisor %>
</p>

<%= link_to 'Edit Student', edit_student_path(@student) %> |
<%= link_to 'Destroy', student_path(:id => @student), method: :delete%>
<%= link_to 'Back', students_path %>

<h2>Plans Of Study:</h2>
<ul>
  <% @student.plans.each do |plan| %>
    <li>
      <%=link_to plan.nameofplan, plan%>
      <%=plan.created_at%>
      <%= button_to 'Destroy Plan', [plan.student, plan],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
              
      <%= button_to 'Submit To Advisor', @student.plans.destroy %>        
  <% end %>
</ul>

<strong>Add a Plan Of Study:</strong>

<%= form_with model: [ @student, @student.plans.build ] do |form| %>
  <p>
   Name Of POS: <%= form.text_field :nameofplan %>
  </p>
  
  <p>
   Name of Semester1: <%= form.text_field :semester1 %>
  </p>
  
  <div class="control-group">
    <%= form.label "Course1a", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course1a, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course1b", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course1b, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course1c", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course1c, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course1d", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course1d, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
  <p>
   Name of Semester2: <%= form.text_field :semester2 %>
  </p>
  
  <div class="control-group">
    <%= form.label "Course2a", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course2a, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course2b", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course2b, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course2c", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course2c, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course2d", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course2d, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
  <p>
   Name of Semester3: <%= form.text_field :semester3 %>
  </p>
  
    <div class="control-group">
    <%= form.label "Course3a", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course3a, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course3b", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course3b, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course3c", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course3c, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course3d", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course3d, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
  <p>
   Name of Semester4: <%= form.text_field :semester4 %>
  </p>
  
  <div class="control-group">
    <%= form.label "Course4a", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course4a, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course4b", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course4b, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course4c", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course4c, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course4d", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course4d, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
  <p>
   Name of Semester5: <%= form.text_field :semester5 %>
  </p>
  
  <div class="control-group">
    <%= form.label "Course5a", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course5a, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course5b", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course5b, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course5c", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course5c, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course5d", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course5d, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
  <p>
   Name of Semester6: <%= form.text_field :semester6 %>
  </p>
  
  <div class="control-group">
    <%= form.label "Course6a", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course6a, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course6b", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course6b, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course6c", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course6c, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course6d", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course6d, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
  <p>
   Name of Semester7: <%= form.text_field :semester7 %>
  </p>
  
  <div class="control-group">
    <%= form.label "Course7a", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course7a, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course7b", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course7b, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course7c", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course7c, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course7d", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course7d, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
  <p>
   Name of Semester8: <%= form.text_field :semester8 %>
  </p>
  
  <div class="control-group">
    <%= form.label "Course8a", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course8a, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course8b", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course8b, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course8c", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course8c, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course8d", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course8d, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
  <p>
   Name of Semester9: <%= form.text_field :semester9 %>
  </p>
  
  <div class="control-group">
    <%= form.label "Course9a", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course9a, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course9b", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course9b, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course9c", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course9c, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course9d", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course9d, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
  <p>
   Name of Semester10: <%= form.text_field :semester10 %>
  </p>
  
  <div class="control-group">
    <%= form.label "Course10a", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course10a, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course10b", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course10b, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course10c", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course10c, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course10d", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course10d, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
  <p>
    
   Name of Semester11: <%= form.text_field :semester11 %>
  </p>
  
  <div class="control-group">
    <%= form.label "Course11a", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course11a, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course11b", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course11b, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course11c", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course11c, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course11d", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course11d, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
  <p>
   Name of Semester12: <%= form.text_field :semester12 %>
  </p>
  
  <div class="control-group">
    <%= form.label "Course12a", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course12a, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course12b", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course12b, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course12c", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course12c, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>
    <div class="control-group">
    <%= form.label "Course12d", class: 'control-label' %>
    <div class="controls">
      <%= form.select(:course12d, options_from_collection_for_select(Course.all, 'name', 'name')) %>
    </div>
  </div>

  <p>
    <%= form.submit %>
  </p>
<% end %>

</p>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Student: <%= @student.email %></h1>

<%= link_to 'Back', students_path %>

<h2>Plans Of Study:</h2>
<ul>
  <% @semesters.each do |semester| %>
    <li>
      <%= link_to semester.name, semester %>
      <%=semester.course1%>
      <%=semester.course2%>
      <%=semester.course3%>
      <%=semester.course4%>
    </li>
  <% end %>
</ul>