config/routes.rb
Rails.application.routes.draw do
  #these constraints are for when we figure out the associations with users to students, programdirectors, professors/advisors
   # constraints Clearance::Constraints::SignedIn.new { |user| user.programdirectors? } do
   # root to: "programdirectors/dashboards#show", as: :programdirectors_root
  #end

 # constraints Clearance::Constraints::SignedIn.new { |user| user.professors? } do
  #  root to: "professors/dashboards#show", as: :professors_root
 # end

 # constraints Clearance::Constraints::SignedIn.new { |user| user.students? } do
  #  root to: "students/dashboards#show", as: :students_root
 # end
  
  resources :notes
  
  resources :comments
  
  resources :discussions
  
  resources :programdirectors
  
  #adds a path under professors: example: https://myappname.com/professors/professorid/student/studentsid
  resources :professors do 
   resources :students
  end
  
  resources :plans
  
  resources :welcome
  
  #adds a path under students: example: https://myappname.com/students/studentid/plan/planid
  resources :students do
   resources :plans
  end
  
  resources :semesters do
   resources :courses, only: [:new, :create, :destroy]
  end
  resources :courses

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  
  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    root to: "landingpage#show", as: :admin_root
  end

  constraints Clearance::Constraints::SignedIn.new do
    root to: "landingpage#show", as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: "landingpage#show"
  end
  
  # get '/', to: 'welcome#index', as: :root
  # get '/sign_up', to: 'users#new', as: :register
  # get '/sign_in', to: 'sessions#new', as: :sign_in
  # post '/login', to: 'sessions#create'
  
  resources :users, only: [:edit, :show, :update]

end

app/models/ability.rb
class Ability
  include CanCan::Ability
#if you are going to use these in the show.html.erb you need to put above the <%link_to 
#<%if can? :actionperform, @model you want to perform it on checking users ability

#also in the controller.rb of function like def edit you would have to put at the bottom

#of the method unauthorized! if cannot? 
  alias_action :create, :read, :update, :destroy, to: :crud
  
  def initialize(user)
  can :read, :all 
  end 
  
end

  
  
  
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :student, class_name => 'User'
  belongs_to :professor, class_name => 'User'
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :course_semesters
    has_many :courses, through: :course_semesters
    validates :name, presence: true
    validates :dept, presence: true
    validates :number, presence: true
    validates :description, presence: true
end

app/models/course_semester.rb
class CourseSemester < ApplicationRecord
    belongs_to :semester
    belongs_to :course
end

app/models/discussion.rb
class Discussion < ApplicationRecord
    has_many :comments
    validates :title, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/plan.rb
class Plan < ApplicationRecord
    belongs_to :student, optional: true
    has_many :semesters
    has_many :courses, through: :semesters
end

app/models/professor.rb
class Professor < ApplicationRecord
    has_many :students
    belongs_to :programdirector
    #belongs_to :users
end

app/models/programdirector.rb
class Programdirector < ApplicationRecord
    has_many :professors
    #belongs_to :users
end

app/models/semester.rb
class Semester < ApplicationRecord
 belongs_to :user
 has_many :course_semesters
 has_many :courses, through: :course_semesters
 validates_presence_of :name
end

app/models/student.rb
class Student < ApplicationRecord
    #belongs_to :users
    has_many :plans
    belongs_to :professor
    #has_many :semesters, through: :plans
   # has_many :courses, through: :semesters
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  validates_presence_of :email, :encrypted_password
  has_many :comments
  has_many :semesters
  # has_many :users, :class_name => 'Student', :foreign_key => 'student_id'
  # has_many :advisors, :class_name => 'Professor', :foreign_key => 'advisor_id'
  
  ROLES = ['Student', 'Professor', 'Director', 'Admin']

  enum role: ["Student", "Professor", "Director", "Admin"]
  
  def self.students
    User.where(role: "Student")
  end
  
  def advisor
    User.find(self.advisor_id)
  end
  
  def students
    User.where(advisor_id: self.id)
  end
  
  def student?
    self.role == "Student"
  end
  
  def admin?
    self.role == "Admin"
  end
  
  def self.professors
    User.where(role: "Professor")
  end
  
  private
  
  def user_params
    params.require(:user).permit(
      :email, 
      :password, 
      :role
    )
  end
end

app/controllers/programdirectors_controller.rb
class ProgramdirectorsController < ApplicationController
  def index
    @professor = User.professors
    @students = User.students
    @courses = []#Course.all
  end
  
  def show
    @professor = Professor.find(params[:id])
    @students = Student.find(params[:id])
    @course = Course.find(params[:id])
  end
  
  def new
    @course = Course.new
    @student = Student.new
    @professor = Professor.new
  end

  def create
   @course = Course.new(course_params)

    if @course.save
      redirect_to @course
    else
      render :new
    end
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: "Professor was successfully created." }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
    @programdirector = Programdirector.find(params[:id])
  end

  def update
    @programdirector = Programdirector.find(params[:id])

    if @programdirector.update(programdirector_params)
      redirect_to @programdirector
    else
      render :edit
    end
  end
  
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    redirect_to root_path
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: "Professor was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  private
    def programdirector_params
      params.require(:programdirector).permit(:Name, :CWID)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/programdirectors_helper.rb
module ProgramdirectorsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/programdirectors/_form.html.erb
<%= form_with(model: programdirector) do |form| %>
  <% if programdirector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(programdirector.errors.count, "error") %> prohibited this programdirector from being saved:</h2>

      <ul>
        <% programdirector.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    Name: <%= form.text_field :Name %>
    <% programdirector.errors.full_messages_for(:Name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
   CWID: <%= form.text_field :CWID %>
    <% programdirector.errors.full_messages_for(:CWID).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/programdirectors/edit.html.erb
<h1>Editing Programdirector</h1>

<%= render 'form', programdirector: @programdirector %>

<%= link_to 'Show', @programdirector %> |
<%= link_to 'Back', programdirectors_path %>

app/views/programdirectors/index.html.erb
<h1>Professors</h1>

<table>
  <thead>
    <tr>
     <thead>
    <tr>
      <th>Name</th>
      <th>Cwid</th>
      <th colspan="2"></th>
    </tr>
  </thead>
    </tr>
  </thead>

  <tbody>
    <% @professor.each do |professor| %>
      <tr>
        <td><%= link_to professor.name, professor_path(professor) %></td>
        <td><%= professor.cwid %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cwid</th>
      <th>Concentration</th>
      <th>Advisor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.name, student_path(student) %></td>
        <td><%= student.cwid %></td>
        <td><%= student.concentration %></td>
        <% if student.advisor_id %>
          <% advisor = student.advisor %>
          <td><%= link_to advisor.name, professor_path(advisor) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1>Courses</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Section</th>
      <th>Number</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 <tbody>
  <% @courses.each do |course| %>
   <tr>
       <td><%=course.prefix%></td>
       <td><%= link_to course.name, course %></td>
       <td><%=course.section%></td>
       <td><%=course.number%></td>
      <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</tbody>
</table>
<%= link_to "New Course", new_course_path %>

app/views/programdirectors/new.html.erb
<h1>New Programdirector</h1>

<%= render 'form', programdirector: @programdirector %>

<%= link_to 'Back', programdirectors_path %>

app/views/programdirectors/show.html.erb
<h1><%= @programdirector.Name %></h1>

<p>Name: <%= @professor.Name %></p>
<p>CWID: <%= @professor.CWID %></p>
<p><%= @programdirector.created_at %></p>
<ul>
  <li><%= link_to "Edit", edit_programdirector_path(@programdirector) %></li>

<li><%= link_to "Destroy Programdirector", programdirector_path(@programdirector),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>